spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=false